version: '3'
services:

  server-app:
    container_name: server-app
    build: ./server_app
    command: python3 -m flask run --host=0.0.0.0 --debug
    ports:
      - 5000:5000
    volumes:
      - ./server_app:/app
    environment:
      - FLASK_APP=app/app.py
    env_file:
      - .env
    depends_on:
      - allergen-safe-db

  celery:
    container_name: celery
    build: ./server_app
    command: python3 -m celery worker --loglevel=info
    volumes:
      - ./server_app:/app
    environment:
      - CELERY_APP=app.celery_app
    env_file:
      - .env
    depends_on:
      - server-app
      - redis

  ai-app:
    container_name: ai-app
    build: ./ai_app
    ports:
      - 80:80
    volumes:
      - ./ai_app:/app
    env_file:
      - .env

  allergen-safe-db:
    container_name: allergen-safe-db
    image: postgres:15  
    ports:
      - 5432:5432
    volumes:
      - ./temp/psqlDB:/var/lib/postgresql/data
    env_file:
      - .env

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379

  adminer:
    container_name: adminer
    image: adminer:latest
    ports:
      - 8082:8080
    env_file:
      - .env
    depends_on:
      - allergen-safe-db