version: '3'
services:
  
  app:
    container_name: app
    build: ./server_app
    ports:
      - 5000:5000
    environment:
      - SECRET_KEY=$SERVER_SECRET_KEY
      - DATABASE_URI=$SERVER_DATABASE_URI
    volumes:
      - ./server_app:/app
    env_file:
      - .env
    depends_on:
      - allergen-safe-db

  allergen-safe-db:
    container_name: allergen-safe-db
    image: postgres:15  
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    volumes:
      - ./temp/psqlDB:/var/lib/postgresql/data
    env_file:
      - .env

  adminer:
    container_name: adminer
    image: adminer:latest
    ports:
      - 8082:8080
    env_file:
      - .env
    depends_on:
      - allergen-safe-db